LMS/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('main/', include(('main.urls', 'main'), namespace='main')),
    path('librarian/', include(('librarian.urls', 'librarian'), namespace='librarian')),
  

    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

librarian/urls.py
from django.urls import path

from . import views

app_name = 'librarian'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('students/', views.students, name='students'),
    path('manage_book/', views.manage_book, name='manage_book'),
    path('book_requests/', views.book_requests, name='book_requests'),
    path('accept_req/<int:id>', views.accept_request, name="accept_request"),
    path('book_tracking/', views.book_tracking, name="book_tracking"),
    path('issue_book/<int:req_id>', views.issue_book, name="issue_book"),
    path('return_book/<int:req_id>', views.return_book, name="return_book"),
    path('active_student/<int:student_id>', views.active_student, name="active_student"),
    path('update_book_info/', views.update_book_info, name="update_book_info"),
    path('remove_book/<int:book_id>', views.remove_book, name="remove_book"),
    path('comments/', views.comments, name="comments")

]

librarian/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    def __str__(self):
        return self.user.username

librarian/views.py
import random

from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils import timezone

from LMS import settings
from main.models import Book, BookRequest, OtpVerification, Category, Comment
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from accounts.models import StudentProfile
from django.contrib import messages
from django.http import JsonResponse
from django.core.paginator import Paginator
# Create your views here.

@staff_member_required
def dashboard(request):
    total_students = StudentProfile.objects.all().count()
    total_books = Book.objects.all().count()
    total_categories = Category.objects.all().count()
    issued_books = BookRequest.objects.filter(status="accepted").count()
    context = {
        "total_students": total_students,
        "total_books": total_books,
        "total_categories": total_categories,
        "issued_books": issued_books
    }
    return render(request, 'librarian/index.html', context)
@staff_member_required
def students(request):
    student_list = StudentProfile.objects.all()
    paginator = Paginator(student_list, 10)
    return render(request, 'librarian/studentList.html', {'students': student_list})
@staff_member_required
def manage_book(request):
    books = Book.objects.all()
    paginator = Paginator(books, 10)

    page_num = request.GET.get("page")
    page_obj = paginator.get_page(page_num)
    context = {
        'books': page_obj,
    }
    return render(request, 'librarian/manageBooks.html', context)

@staff_member_required
def book_requests(request):
    book_request_list = BookRequest.objects.order_by('-id')
    context = {
        'requests': book_request_list,
        "status" : BookRequest.STATUS_OPTIONS,
    }
    return render(request, 'librarian/bookRequests.html', context)

@staff_member_required
def accept_request(request, id):
    book_req = BookRequest.objects.get(id=id)
    book_req.status = "accepted"
    book_req.save()

    otp = random.randint(100000, 999999)
    otpVerification = OtpVerification.objects.create(
        user=book_req.student,
        req=book_req,
        otp=otp,
    )
    otpVerification.send_at = timezone.now()
    otpVerification.save()

    # send otp
    name = book_req.student.name
    email = book_req.student.user.email
    template = render_to_string(
        'otp_email.html',
        {'name': name, 'otp': otp, 'action': "Book verification", 'book_name': book_req.book.title}
    )
    send_mail(
        'Otp for confirm Book',
        template,
        settings.EMAIL_HOST_USER,
        [email],
        fail_silently=False,
        html_message=template
    )

    return redirect("librarian:book_requests")

@staff_member_required
def book_tracking(request):
    if request.method == "POST":
        otp = request.POST.get('otp')
        query_otp = OtpVerification.objects.filter(otp=otp).first()

        if query_otp:
            book_request = query_otp.req
            return render(request, 'librarian/bookTracking.html', {"book_req": book_request})
        else:
            messages.warning(request, "No book records found")
            return redirect("librarian:dashboard")

@staff_member_required
def issue_book(request, req_id):
    book_req = BookRequest.objects.get(id=req_id)
    book_req.status = "received"
    book_req.issue_date = timezone.now()
    book_req.return_date = timezone.now() + timezone.timedelta(days=book_req.book_time)
    book_req.save()

    return redirect('librarian:book_requests')

@staff_member_required()
def return_book(request, req_id):
    book_req =  BookRequest.objects.get(id=req_id)
    book_req.status = "returned"
    book_req.save()

    return redirect('librarian:book_requests')

@staff_member_required
def active_student(request, student_id):
    student = StudentProfile.objects.get(id=student_id)
    student.is_active = True
    student.save()
    return redirect("librarian:students")


@staff_member_required
def update_book_info(request):
    if request.method == "POST":
        main_id = request.POST.get("id", None)
        if main_id:
            obj = Book.objects.get(id=main_id)
        else:
            obj = Book()

        obj.title = request.POST.get("title")
        obj.author = request.POST.get("author")
        obj.desc = request.POST.get("desc")
        obj.pages = request.POST.get("pages")
        obj.count = request.POST.get("count")
        obj.book_id = request.POST.get("book_id")
        obj.issued = request.POST.get("issued")

        # Handle category
        category_name = request.POST.get("category")
        cat = Category.objects.filter(name__icontains=category_name).first()
        if cat:
            obj.category = cat
        else:
            obj.category = Category.objects.create(name=category_name, desc="default")

        # Handle image upload
        image = request.FILES.get("image")
        if image:
            obj.image = image

        # Save the updated book object
        obj.save()

        return redirect("librarian:manage_book")

@staff_member_required
def remove_book(request, book_id):
    book = Book.objects.get(id=book_id)
    book.delete()
    return redirect("librarian:manage_book")


@staff_member_required
def comments(request):
    comment = Comment.objects.all()
    context = {
        "comments": comment
    }
    return render(request, "librarian/comments.html", context)

templates/librarian/bookTracking.html
{% extends "librarian/dashboard.html" %}
{% load static %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <table class="table table-borderless">
                <tr>
                    <th>Book Name:</th>
                    <td>{{ book_req.book.title }}</td>
                </tr>
                <tr>
                    <th>Student Name:</th>
                    <td>{{ book_req.student.name }}</td>
                </tr>
                <tr>
                    <th>Requested for:</th>
                    <td>{{ book_req.book_time }} Days</td>
                </tr>
                <th>Status</th>
                {% if book_req.status == 'accepted' or book_req.status == 'received' or book_req.status == 'returned'  %}
                    <td><span class="badge text-bg-success">{{ book_req.status }}</span></td>
                {% else %}
                    <td><span class="badge text-bg-danger">{{ book_req.status }}</span></td>
                {% endif %}
                <tr>
                    <th>Issue Date:</th>
                    <td>{{ book_req.issue_date }}</td>
                </tr>
                <tr>
                    <th>Return Date:</th>
                    <td>{{ book_req.return_date }}</td>
                </tr>
                <tr>
                    <th></th>
                    <td>
                        {% if book_req.status == "accepted" %}
                            <a class="btn btn-outline-dark" href="{% url 'librarian:issue_book' book_req.id %}">Issue</a>
                        {% endif %}
                        {% if book_req.status == "received" %}
                            <a class="btn btn-outline-dark" href="{% url 'librarian:return_book' book_req.id %}">Return</a>
                        {% endif %}</td>
                </tr>
            </table>

        </div>
    </div>
{% endblock %}

templates/librarian/comments.html
{% extends "librarian/dashboard.html" %}
{% load static %}

{% block content %}
<table class="table table-responsive">
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Book</th>
        <th>Date & Time</th>
        <th>Comment</th>
        <th>Action</th>
    </tr>
    {% for comment in comments %}
    <tr>
        <td>{{forloop.counter}}</td>
        <td>{{comment.student.name}}</td>
        <td>{{comment.book.title}}</td>
        <td>{{comment.add_at}}</td>
        <td>{{comment.text}}</td>
        <td><button class="btn btn-secondary"><i class="fa fa-edit"></i></button></td>
    </tr>
    {% endfor %}
    <tr>
        <td>2</td>
        <td>Mahmud Hasan</td>
        <td>Python programming</td>
        <td>15 jul 2024 12:10pm</td>
        <td>This book is awesome.</td>
        <td><button class="btn btn-secondary"><i class="fa fa-edit"></i></button></td>
    </tr>
    <tr>
        <td>3</td>
        <td>Mahmud Hasan</td>
        <td>Python programming</td>
        <td>15 jul 2024 12:10pm</td>
        <td>This book is awesome.</td>
        <td><button class="btn btn-secondary"><i class="fa fa-edit"></i></button></td>
    </tr>
    <tr>
        <td>4</td>
        <td>Mahmud Hasan</td>
        <td>Python programming</td>
        <td>15 jul 2024 12:10pm</td>
        <td>This book is awesome.</td>
        <td><button class="btn btn-secondary"><i class="fa fa-edit"></i></button></td>
    </tr>
    <tr>
        <td>5</td>
        <td>Mahmud Hasan</td>
        <td>Python programming</td>
        <td>15 jul 2024 12:10pm</td>
        <td>This book is awesome.</td>
        <td><button class="btn btn-secondary"><i class="fa fa-edit"></i></button></td>
    </tr>
</table>
{% endblock %}

templates/librarian/dashboard.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel Sidebar Menu</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <style>
        #content.active{
            padding-left: 0;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>

<div class="wrapper">
    <!-- Sidebar -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <h3>Admin Panel</h3>
        </div>
        <ul class="list-unstyled components">
            <li class="active">
                <a href="{% url 'librarian:dashboard' %}">Dashboard</a>
            </li>
            <li>
                <a href="{% url 'librarian:students' %}">Student List</a>
            </li>
            <li>
                <a href="{% url 'librarian:manage_book' %}">Manage Books</a>
            </li>
            <li>
                <a href="{% url 'librarian:book_requests' %}">Book Requests</a>
            </li>
            <li>
                <a type="button" data-bs-toggle="modal" data-bs-target="#ModalBookTrack">Book Tracking</a>
            </li>
            <li>
                <a href="{% url 'librarian:comments' %}">Comments / Ratings</a>
            </li>
            <li>
                <a href="#settings">Settings</a>
            </li>
        </ul>
    </nav>

    <!-- Modal for book tracking -->
    <div class="modal fade" id="ModalBookTrack" tabindex="-1" aria-labelledby="ModalBookTrackLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="ModalBookTrackLabel">Book Tracking</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'librarian:book_tracking' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="d-flex flex-column">
                            <label for="otp">Enter the otp:</label>
                            <input type="text" name="otp" class="form-control">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Track</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Page Content -->
    <div id="content">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show my-0" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button type="button" id="sidebarCollapse" class="btn btn-info btn-toggle">
                    <i class="fas fa-align-left"></i>
                    <span>Toggle Sidebar</span>
                </button>
            </div>
        </nav>
        <!-- Page Content -->
        <div class="container">
            {% block content %}{% endblock %}
        </div>


    </div>
</div>
<!-- Bootstrap JS and Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
    // Check if the device width is less than 800px
    if ($(window).width() < 800) {
        $('#sidebar').addClass('active');
        $('#content').addClass('active');
    }

    // Toggle sidebar on button click
    $('#sidebarCollapse').on('click', function () {
        $('#sidebar').toggleClass('active');
        $('#content').toggleClass('active');
    });
    
    // Listen for window resize to ensure responsiveness
    $(window).resize(function() {
        if ($(window).width() < 800) {
            $('#sidebar').addClass('active');
            $('#content').addClass('active');
        } else {
            $('#sidebar').removeClass('active');
            $('#content').removeClass('active');
        }
    });
});


    // active menu page highlight
    $(document).ready(function () {
        var url = window.location;
        $('ul.components li').removeClass('active');
        $('ul.components a').filter(function () {
            return this.href == url;
        }).closest('li').addClass('active');
    });


</script>
{% block js %}{% endblock %}
</body>
</html>

templates/librarian/manageBooks.html
{% extends "librarian/dashboard.html" %}
{% load static %}
{% block content %}
    <div class="table-title-container d-flex justify-content-between">
        <h2>Manage Books</h2>
        <div class="table-search-container d-flex w-50 gap-2">
            <input type="text" class="form-control" id="search-box" placeholder="Search">
            <!-- Button trigger add modal -->
            <button class="btn btn-info" data-bs-toggle="modal" data-bs-target="#addBookModal"><i
                    class="fa fa-plus"></i></button>


            <!-- Modal -->
            <div class="modal fade" id="addBookModal" tabindex="-1" aria-labelledby="addBookModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="addBookModalLabel">Add book</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                        </div>
                        <form action="{% url 'librarian:update_book_info' %}" method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="modal-body">
                                <div class="mb-3">
                                    <label for="exampleFormControlInput1" class="form-label fw-bold">Title:</label>
                                    <input type="text" class="form-control" name="title" required>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlInput1" class="form-label fw-bold">Author
                                        name:</label>
                                    <input type="text" class="form-control" name="author" required>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlTextarea1" class="form-label">Description:</label>
                                    <textarea class="form-control" name="desc" rows="3"></textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlInput1" class="form-label fw-bold">Category:</label>
                                    <input type="text" class="form-control" name="category" required>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlInput1" class="form-label fw-bold">Book image:</label>
                                    <input type="file" class="form-control" name="image" required>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlInput1" class="form-label fw-bold">Pages:</label>
                                    <input type="number" class="form-control" name="pages" required>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlInput1" class="form-label fw-bold">Count:</label>
                                    <input type="number" class="form-control" name="count" required>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlInput1" class="form-label fw-bold">Book id:</label>
                                    <input type="number" class="form-control" name="book_id" required>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlInput1" class="form-label fw-bold">Issued:</label>
                                    <input type="number" class="form-control" name="issued" required>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Close
                                </button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card mt-2">
        <table class="table table-striped" id="equipment-table">
            <thead>
            <tr>
                <th>#</th>
                <th scope="col">Book ID</th>
                <th scope="col">Book Name</th>
                <th scope="col">Writer</th>
                <th scope="col">Available</th>

                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for book in books %}
                <tr>
                    <th style="text-align: center;"><img src="{{ book.image.url }}" alt=""></th>
                    <td scope="row">{{ book.book_id }}</td>
                    <td class="truncate-text">{{ book.title }}</td>
                    <td class="truncate-text">{{ book.author }}</td>
                    <td>{{ book.available }} / {{ book.count }}</td>
                    <td><span role="button" data-bs-toggle="modal" data-bs-target="#Modalfor{{ book.id }}"><i
                            class="fa fa-edit"></i></span></td>
                </tr>

                <div class="modal fade" id="Modalfor{{ book.id }}" tabindex="-1" aria-labelledby="addBookModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="addBookModalLabel">Manage book</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <form action="{% url 'librarian:update_book_info' %}" method="post"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="modal-body">
                                    <div class="mb-3">
                                        <label for="exampleFormControlInput1" class="form-label fw-bold">Title:</label>
                                        <input type="text" class="form-control" value="{{ book.title }}" name="title"
                                               required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleFormControlInput1" class="form-label fw-bold">Author
                                            name:</label>
                                        <input type="text" class="form-control" value="{{ book.author }}" name="author"
                                               required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleFormControlTextarea1" class="form-label">Description:</label>
                                        <textarea class="form-control" rows="3" name="desc">{{ book.desc }}</textarea>
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleFormControlInput1"
                                               class="form-label fw-bold">Category:</label>
                                        <input type="text" class="form-control" value="{{ book.category }}"
                                               name="category" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleFormControlInput1" class="form-label fw-bold">Book
                                            image:</label>
                                        <img class="form-control" src="{{ book.image.url }}"
                                             style="height:100px; width: 100px">
                                        <input type="file" class="form-control" name="image">
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleFormControlInput1" class="form-label fw-bold">Pages:</label>
                                        <input type="number" class="form-control" name="pages" value="{{ book.pages }}"
                                               required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleFormControlInput1" class="form-label fw-bold">Count:</label>
                                        <input type="number" class="form-control" name="count" value="{{ book.count }}"
                                               required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleFormControlInput1" class="form-label fw-bold">Book
                                            id:</label>
                                        <input type="number" class="form-control" name="book_id"
                                               value="{{ book.book_id }}" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleFormControlInput1" class="form-label fw-bold">Issued:</label>
                                        <input type="number" class="form-control" name="issued"
                                               value="{{ book.issued }}" required>
                                    </div>
                                    <input type="hidden" value="{{ book.id }}" name="id">
                                </div>
                                <div class="modal-footer">

                                    <button type="button" class="btn btn-secondary"
                                            data-bs-dismiss="modal">Close
                                    </button>
                                    <a href="{% url 'librarian:remove_book' book.id %}"><button type="button" class="btn btn-danger">Remove</button></a>
                                    <button type="submit" class="btn btn-primary">Save changes</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}


            </tbody>
        </table>


    </div>


    <nav aria-label="Page navigation example">
        <ul class="pagination my-3 ">
            {% if books.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ books.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
            {% endif %}

            <li class="page-item"><a class="page-link" href="#">{{ books.number }}</a></li>
            <li class="page-item"><a class="page-link disabled" href="#">...</a></li>
            {% if books.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="?page={{ books.paginator.num_pages }}">{{ books.paginator.num_pages }}</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ books.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}

        </ul>
    </nav>


{% endblock %}
{% block js %}
    <script>
        $(document).ready(function () {
            $("#search-box").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#equipment-table tbody tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
        $(document).ready(function () {
            // Truncate book titles
            $('.truncate-text').each(function () {
                var maxLength = 23;
                var text = $(this).text();
                if (text.length > maxLength) {
                    $(this).text(text.substring(0, maxLength) + '...');
                }
            });
        });


    </script>
{% endblock %}
</body>

</html>