LMS/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('main/', include(('main.urls', 'main'), namespace='main')),
    path('librarian/', include(('librarian.urls', 'librarian'), namespace='librarian')),
  

    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup_view, name="signup"),
    path('logout/', views.logout_view, name="logout")
]

main/urls.py
from django.urls import path
from . import views
app_name = "main"
urlpatterns = [
    path("book_by_category/<str:category>", views.book_by_category, name="book_by_category"),
    path("search", views.search, name="search"),
    path("book/<int:book_id>", views.book, name="book"),
    path("all_categories", views.all_categories, name="all_categories"),
    path("student-information", views.student_information, name="student_information"),
    path('request-book/', views.request_book, name='request_book'),
    path('add_to_wishlist/<int:book_id>', views.add_to_wishlist, name="add_to_wishlist"),
    path('remove_from_wishlist/<int:book_id>', views.remove_from_wishlist, name="remove_from_wishlist"),
    path('add_comment/', views.add_comment, name="add_comment")

]

main/models.py
from django.db import models
from autoslug import AutoSlugField


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100, blank=False, null=False)
    slug = AutoSlugField(populate_from='title', unique=True, null=True, blank=True)
    author = models.CharField(max_length=100, blank=False, null=False)
    desc = models.TextField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="books")
    image = models.ImageField(upload_to='books', blank=True, null=True)
    pages = models.IntegerField(blank=True, null=True)
    count = models.IntegerField(blank=True, null=True, default=1)
    book_id = models.CharField(max_length=20, blank=True, null=True)
    issued = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def is_avail(self):
        if self.count > 0:
            return True
        else:
            return False

    def available(self):
        return self.count - self.issued


class HomeBookCarousel(models.Model):
    image = models.ImageField(upload_to="Book_carousel", blank=True, null=True)


class BookRequest(models.Model):
    STATUS_OPTIONS = {
        "pending": "Pending",
        "accepted": "Accepted",
        "rejected": "Rejected",
        "received": "Received",
        "returned": "Returned"
    }
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    student = models.ForeignKey('accounts.StudentProfile', on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_OPTIONS, blank=True, null=True)
    book_time = models.IntegerField(default=0)
    issue_date = models.DateField(blank=True, null=True)
    return_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.book.title} - {self.student.user.username}"


class OtpVerification(models.Model):
    user = models.ForeignKey('accounts.StudentProfile', on_delete=models.CASCADE)
    req = models.ForeignKey('main.BookRequest', on_delete=models.CASCADE, null=True)
    otp = models.CharField(max_length=10)
    send_at = models.DateTimeField(auto_now_add=True)
    is_verified = models.BooleanField(default=False)


class WishList(models.Model):
    student = models.ForeignKey('accounts.StudentProfile', on_delete=models.CASCADE)
    book = models.ForeignKey('main.Book', on_delete=models.CASCADE)
    add_at = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    student = models.ForeignKey('accounts.StudentProfile', on_delete=models.CASCADE)
    book = models.ForeignKey('main.Book', on_delete=models.CASCADE)
    text = models.TextField(blank=True, null=True)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True )
    add_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

templates/allcata.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<style>
    /* Your existing CSS code */
.books_name {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}

</style>
<!-- all catagory book show -->
{% for category in categories %}

<!-- catagory slider 1 -->
<div class="catagory_body_main">

    <div class="row pt-4 pb-2">
        <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12 col-12">
            <h2 class="catagory_name">{{category.name}}</h2>
        </div>
    </div>

    <div class="row">
        <div class="catagory_slider" id="slider{{ forloop.counter }}">
            {% for book in category.books.all %}
            <div class="books_show_card text-center col-3 col-xl-3 col-md-3 col-sm-6 col-6">
                <a href="#"> <img src="{{book.image.url}}" alt="photo"></a>
                <h2 class="books_name pt-3 truncate-text" >{{book.title}}</h2>
                <h2 class="writer">{{book.author}}</h2>
                <p class="available_status">out of stock</p>
                <div class="read_and_read_btn">
                    <a href="{% url 'main:add_to_wishlist' book.id %}" class="wish_list">Wish List</a>
                    <a href="{% url 'main:book' book.id %}" class="read_now">Read Now</a>
                </div>
            </div>
            {% endfor %}




        </div>
    </div>

    <div class="prev_and_next_btn text-center my-4">
        <button class="prev_btn" data-slider="#slider{{ forloop.counter }}">Prev</button>
        <button class="next_btn" data-slider="#slider{{ forloop.counter }}">next</button>
    </div>

</div>
{% endfor %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<Script>
    $(document).ready(function () {
    // Truncate book titles
    $('.truncate-text').each(function () {
        var maxLength = 23;
        var text = $(this).text();
        if (text.length > maxLength) {
            $(this).text(text.substring(0, maxLength) + '...');
        }
    });
});

</Script>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!-- hero slider -->
<div class="row">
    <div class="hero_slider">
        <div class="row">
            <!-- <div class="col-lg-12"> -->
            <div class="hero_slider my-3">
                {% for img in slider_images %}
                <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12 col-12 hero_slider_img">
                    <img src="{{img.image.url}}" alt="" />
                </div>
                {% endfor %}
            </div>
            <!-- </div> -->
        </div>
    </div>
</div>

<!-- 1st book show slider -->
<div class="row">
    <div class="container books_show_main">
        <div class="display_book_cata_and_more d-flex justify-content-between">
            <h2>Top Rated Books List</h2>
            <a href="{% url 'main:all_categories' %}">More</a>
        </div>

        <div class="catagory_slider" id="fontSlider1">
            {% for book in books %}
            <div class="books_show_card text-center col-3 col-xl-3 col-md-3 col-sm-6 col-6">
                <a href="{% url 'main:book' book.id %}"> <img src="{{ book.image.url }}" alt="photo"></a>

            </div>
            {% endfor %}
            

        </div>

        <!-- prev and next  custom button for mobile and tab's only -->
        <div class="prev_and_next_btn text-center my-4">
            <button id="prev_btn" class="my-btn-secondary" data-slider="#fontSlider1">Prev</button>
            <button id="next_btn" class="my-btn-primary" data-slider="#fontSlider1">next</button>
        </div>
        <!-- prev and next  custom button for mobile and tab's only -->

    </div>
</div>

<!-- ..... 2nd...... -->

<div class="row">
    <div class="container books_show_main">
        <div class="display_book_cata_and_more d-flex justify-content-between">
            <h2>Most Read</h2>
            <a href="{% url 'main:all_categories' %}">More</a>
        </div>

        <div class="catagory_slider" id="fontSlider2">

            {% for book in books %}
            <div class="books_show_card text-center col-3 col-xl-3 col-md-3 col-sm-6 col-6">
                <a href="{% url 'main:book' book.id %}"> <img src="{{ book.image.url }}" alt="photo"></a>

            </div>
            {% endfor %}

        </div>

        <!-- prev and next  custom button for mobile and tab's only -->
        <div class="prev_and_next_btn text-center my-4">
            <button id="prev_btn" class="my-btn-primary" data-slider="#fontSlider2">Prev</button>
            <button id="next_btn" class="my-btn-secondary" data-slider="#fontSlider2">next</button>
        </div>
        <!-- prev and next  custom button for mobile and tab's only -->

    </div>
</div>


<!-- 3rd -->


<div class="row">
    <div class="container books_show_main">
        <div class="display_book_cata_and_more d-flex justify-content-between">
            <h2>New Addition</h2>
            <a href="{% url 'main:all_categories' %}">More</a>
        </div>

        <div class="catagory_slider" id="fontSlider3">

            {% for book in books %}
            <div class="books_show_card text-center col-3 col-xl-3 col-md-3 col-sm-6 col-6">
                <a href="{% url 'main:book' book.id %}"> <img src="{{ book.image.url }}" alt="photo"></a>

            </div>
            {% endfor %}
        </div>

        <!-- prev and next  custom button for mobile and tab's only -->
        <div class="prev_and_next_btn text-center my-4">
            <button class="my-btn-primary" id="prev_btn" data-slider="#fontSlider3">Prev</button>
            <button class="my-btn-secondary" id="next_btn" data-slider="#fontSlider3">next</button>
        </div>
        <!-- prev and next  custom button for mobile and tab's only -->

    </div>
</div>



{% endblock %}

templates/logInForm.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login form - membarship form</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <!-- fondawsome cdn link -->
    <!-- fontawsome-cdn-links -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
      

    <!-- main css file link here -->
    <link rel="stylesheet" href="{% static 'css/main.css'%}" />
  </head>
  <body>


    <main class="dpiL_login_form">
      <section class="log_in_form_main">

        <form action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            <h2 class="text-center">দিনাজপুর পলিটেকনিক ইন্সিটিউট</h2>
            <h3 class="text-center ">লাইব্রেরী</h3>

            <div class="input_group mx-3">
                <span><i class="fa-solid fa-user"></i></span>
                <input type="text" placeholder="Your UserName" name="username" required>
            </div>

            <div class="input_group mx-3 mt-3">
                <span><i class="fa-solid fa-lock"></i></span>
                <input type="password" placeholder="Your Password" name="password" required>
            </div>

           <div class="forget_pass mx-3 py-3 ">
            <a href="#" class="text-decoration-none">Forget Password?</a>
           </div>

           <div class="login_btn mx-3">
            <button type="submit">Log In</button>
           </div>


        </form>

      <div class="not_member mx-3 text-center py-3">
        <p>Not a member ? <span><a href="{% url 'accounts:signup' %}">SignUp Now</a></span></p>
      </div>

    </section>
    </main>

    
  
    <!-- bootstrap js file line here -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <!-- <script src="./node_modules/bootstrap/dist/js/bootstrap.min.js"></script> -->

    <!-- jquary cdn link here -->
    <script
      src="https://code.jquery.com/jquery-3.7.1.min.js"
      integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
      crossorigin="anonymous"
    ></script>

    <script src="{%  static 'js/main.js' %}"></script>
  </body>
</html>

templates/manageBooks.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel Sidebar Menu</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="assets/css/custom.css">
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Admin Panel</h3>
            </div>
            <ul class="list-unstyled components">
                <li>
                    <a href="index.html">Dashboard</a>
                </li>
                <li>
                    <a href="studentList.html">Student List</a>
                </li>
                <li class="active">
                    <a href="#manageBooks">Manage Books</a>
                </li>
                <li>
                    <a href="#manageBooks">Book Requests</a>
                </li>
                <li>
                    <a href="#manageBooks">Comments / Ratings</a>
                </li>
                <li>
                    <a href="#settings">Settings</a>
                </li>
            </ul>
        </nav>
        <!-- Page Content -->
        <div id="content">

            <!-- Page Content -->
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">
                        <button type="button" id="sidebarCollapse" class="btn btn-secondary btn-toggle">
                            <i class="fas fa-align-left"></i>

                        </button>
                    </div>
                </nav>
                <div class="table-title-container d-flex justify-content-between">
                    <h2>Manage Books</h2>
                    <div class="table-search-container d-flex w-50 gap-2">
                        <input type="text" class="form-control" id="search-box" placeholder="Search">
                         <!-- Button trigger add modal -->
                        <button class="btn btn-info" data-bs-toggle="modal" data-bs-target="#addBookModal"><i class="fa fa-plus"></i></button>

                       

                        <!-- Modal -->
                        <div class="modal fade" id="addBookModal" tabindex="-1" aria-labelledby="addBookModalLabel"
                            aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="addBookModalLabel">Modal title</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        ...
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-bs-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card mt-2">
                    <table class="table table-striped" id="equipment-table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th scope="col">Book ID</th>
                                <th scope="col">Book Name</th>
                                <th scope="col">Writer</th>
                                <th>Sub. Code</th>
                                <th scope="col">Available</th>

                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {{books}}
                            {% for book in books %}
                            <tr>
                                <th style="text-align: center;"><img src="{{book.image.url}}"
                                        alt=""></th>
                                <td scope="row">{{ book.book_id }}</td>
                                <td>{{ book.title }}</td>
                                <td>{{ book.author }}</td>
                                <td>{{ book.available }}</td>
                                <td><span class="cursor-pointer "><i class="fa fa-edit"></i></span></td>
                            </tr>
                            {% endfor %}

                  


                        </tbody>
                    </table>
                    Mahamud
                </div>

            </div>
        </div>
    </div>
    <!-- Bootstrap JS and Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
                $('#content').toggleClass('active');
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $("#search-box").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#equipment-table tbody tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });

       


    </script>
</body>

</html>

templates/otp_email.html
<div style="font-family: Helvetica,Arial,sans-serif;line-height:2">
    <div style="margin:50px auto;width:90%;padding:20px 0; max-width: 800px;">
        <div style="border-bottom:1px solid #eee">
            <a href="" style="font-size:1.4em;color: #00466a;text-decoration:none;font-weight:600">Dinajpur Polytechnic Institute</a>
        </div>
        <p style="font-size:1.1em">Hi, {{ name }}</p>
        <p>Your book request for {{ book_name }} has been accepted. Please visit library for complete the {{ action }}.
            </p>
        <h2 style="background: #00466a;margin: 0 auto;width: max-content;padding: 0 10px;color: #fff;border-radius: 4px;">{{ otp }}</h2>
        <p style="font-size:0.9em;">Regards, <br/><b>DPI</b></p>
        <hr style="border:none;border-top:1px solid #eee"/>
        <div style="float:right;padding:8px 0;color:#aaa;font-size:0.8em;line-height:1;font-weight:300">
            <p>Dinajpur Polytechnic Institute</p>
            <p>Dinajpur,</p>
            <p>Bangladesh</p>
        </div>
    </div>
</div>

templates/readBooks.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <style>
    a{
        text-decoration: none;
        color: black;
    }
    
    </style>
{% endblock %}
{% block body %}

    <!-- booking applyed boooks form using her username -->

    <main class="read_books mt-3">
        <div class="container">
            <div class="row shadow rounded py-3" style="background: #F1E1C2;">
                <div class="col-4">
                    <img class="img-fluid" src="{{ book.image.url }}" alt="">
                </div>
                <div class="col-8 py-2">
                    <h3>{{ book.title }}</h3>
                    <h4>Author : {{ book.author }}</h4>
                    <p>{{ book.desc }}</p>
                    <p>Pages : {{ book.pages }}</p>
                    {% if not user.is_staff and user.studentprofile.is_active %}
                        <form action="{% url 'main:request_book' %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-success" type="submit">Request for this book</button>
                            <input type="hidden" value="{{ book.id }}" name="book_id">
                            <input type="number" class="form-control w-25 d-inline" name="days" value="3">
                        </form>
                    
                    {% else %}
                    <div class="alert alert-danger">You can not Request for this book</div>
                    {% endif %} 
                </div>
            </div>
            <div class="row my-5">
                <h2>Book Holders</h2>
                <table class="table table-borderless">
                {% if book_holders %}
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Issue Date</th>
                        <th scope="col">Time Remaining</th>
                    </tr>
                    </thead>
                    <tbody>
                    
                    {% for item in book_holders %}
                    <tr>
                        <th scope="row">1</th>
                        <td>{{ item.student.name }}</td>
                        <td>{{ item.issue_date }}</td>
                        <td>{{ item.book_time }} Days</td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <div class="alert alert-danger">
                        No book holders yet.
                    </div>
                    {% endif %}

                    </tbody>
                </table>
            </div>
            <div class="row">
                <h2>Comments({{book.comment_set.count}})</h2>

                <form action="{% url 'main:add_comment' %}" method="post">
                    {% csrf_token %}
                <div class="row my-2 mx-2 p-2" >
                    <div class="col-10" style="padding: 0 !important;">
                        <input type="text" class="comment-input" name="comment" placeholder="Share your thoughts about this book." >
                    </div>
                    <div class="col-2" style="padding: 0 !important;">
                        <input type="submit" class="my-btn-secondary my-btn-right" value="Comment"  >
                    </div><input type="hidden" name="book_id" value="{{ book.id }}">
                </div>
        </form>
        {% for comment in book.comment_set.all %}

        {% include 'components/comment.html' %}
        
        {% endfor %}

                
                
            </div>
            <div class="col-12 " style="position: relative;">
                <button class="my-btn-primary" style="width: 150px; position: absolute;left: 0; right: 0; margin: auto;">Load more</button>
            </div>
            
        </div>
    </main>


{% endblock %}

templates/signupForm.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sign up form - membarship form</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <!-- fondawsome cdn link -->
    <!-- fontawsome-cdn-links -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />


    <!-- main css file link here -->
    <link rel="stylesheet" href="{% static 'css/main.css'%}" />
  </head>
  <body>


    <main class="dpiL_login_form">
      <section class="log_in_form_main">

        <form action="{% url 'accounts:signup' %}" method="post">
            {% csrf_token %}
            <h2 class="text-center">দিনাজপুর পলিটেকনিক ইন্সিটিউট</h2>
            <h3 class="text-center ">লাইব্রেরী</h3>

            <div class="input_group mx-3">
                <span><i class="fa-solid fa-user"></i></span>
                <input type="text" placeholder="Your UserName" name="username" required>
            </div>

            <div class="input_group mx-3 mt-3">
                <span><i class="fa-solid fa-lock"></i></span>
                <input type="password" placeholder="New Password" name="password" required>
            </div>

            <div class="input_group mx-3 mt-3">
                <span><i class="fa-solid fa-lock"></i></span>
                <input type="password" placeholder="Confirm Password" name="password2" required>
            </div>



           <div class="login_btn m-3">
            <button type="submit">Signup</button>
           </div>


        </form>

      <div class="not_member mx-3 text-center py-3">
        <p>Already a member ? <span><a href="{% url 'accounts:login' %}">Login Now</a></span></p>
      </div>

    </section>
    </main>



    <!-- bootstrap js file line here -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <!-- <script src="./node_modules/bootstrap/dist/js/bootstrap.min.js"></script> -->

    <!-- jquary cdn link here -->
    <script
      src="https://code.jquery.com/jquery-3.7.1.min.js"
      integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
      crossorigin="anonymous"
    ></script>

    <script src="{%  static 'js/main.js' %}"></script>
  </body>
</html>

templates/singlecata.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<style>
    /* Your existing CSS code */
.books_name {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}

</style>
<!-- single page's search result or department name when user attempt to search-->
<div class="row">
    <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12 col-12">
        {% if operation == "search" %}
        <h2 class="pt-4 pb-5">Search Result for : {{text}}</h2>
        {% else %}
        <h2 class="pt-4 pb-5">Category : {{category}}</h2>
        <h2 class="pt-3 pb-5 d-none">Department Name</h2>
        {% endif %}
    </div>
</div>

<!-- catagory slider 1 -->
<div class="catagory_body_main">
    <!-- search result books show here -->
    <div class="row catagory_slider py-3">
        {% for book in books %}
            <div class="books_show_card text-center col-lg-4 col-3 col-xl-3 col-md-4 col-sm-6 col-6 py-3">
                <a href="#"><img src="{{book.image.url}}" alt="photo"></a>
                <h2 class="books_name pt-3 truncate-text">{{book.title}}</h2>
                <h2 class="writer">{{book.author}}</h2>
                <p class="available_status">Available: {{book.count}}</p>
                <div class="read_and_read_btn">
                    <a href="{% url 'main:add_to_wishlist' book.id %}" class="wish_list my-btn my-btn-secondary .my-btn-sm">Wish List</a>
                    <a href="{% url 'main:book' book.id %}" class="read_now my-btn-primary .my-btn-sm">Read Now</a>
                </div>
            </div>
        {% endfor %}
    </div>


</div>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<Script>
    $(document).ready(function () {
    // Truncate book titles
    $('.truncate-text').each(function () {
        var maxLength = 23;
        var text = $(this).text();
        if (text.length > maxLength) {
            $(this).text(text.substring(0, maxLength) + '...');
        }
    });
});

</Script>

{% endblock %}